### PR TITLE
CLD-8575: Force aws credentials refresh before they expire

### PR DESCRIPTION
**Pull request by andrleite**
#### Summary
The current Minio behavior of the `Get` function is that if you attempt to use an expired credential, the first `Get` call will return an error because the cached credentials are still technically expired. The credentials will only be refreshed after subsequent calls.
To avoid errors in Mattermost in this PR we will proactively force a refresh before using the credentials.

#### Ticket Link
Fixes https://mattermost.atlassian.net/browse/CLD-8575

### CODE REVIEW

**Comment by agnivade** [comment]
> The current Minio behavior of the Get function is that if you attempt to use an expired credential, the first Get call will return an error because the cached credentials are still technically expired.

I am not sure I understand. This is the implementation of Get

```go
func (c *Credentials) Get() (Value, error) {
	if c == nil {
		return Value{}, nil
	}

	c.Lock()
	defer c.Unlock()

	if c.isExpired() {
		creds, err := c.provider.Retrieve()
		if err != nil {
			return Value{}, err
		}
		c.creds = creds
		c.forceRefresh = false
	}

	return c.creds, nil
}
```

So if the creds are expired, we call Retrieve to refresh the credentials. And you are essentially doing the same thing by calling `isExpired()` and then manually calling `Expire()` which will just set `forceRefresh` to true.

Can you clarify?

**Comment by andrleite** [comment]
> > The current Minio behavior of the Get function is that if you attempt to use an expired credential, the first Get call will return an error because the cached credentials are still technically expired.
> 
> I am not sure I understand. This is the implementation of Get
> 
> ```go
> func (c *Credentials) Get() (Value, error) {
> 	if c == nil {
> 		return Value{}, nil
> 	}
> 
> 	c.Lock()
> 	defer c.Unlock()
> 
> 	if c.isExpired() {
> 		creds, err := c.provider.Retrieve()
> 		if err != nil {
> 			return Value{}, err
> 		}
> 		c.creds = creds
> 		c.forceRefresh = false
> 	}
> 
> 	return c.creds, nil
> }
> ```
> 
> So if the creds are expired, we call Retrieve to refresh the credentials. And you are essentially doing the same thing by calling `isExpired()` and then manually calling `Expire()` which will just set `forceRefresh` to true.
> 
> Can you clarify?

You're right! I got confused and thought it'd try at least once with expired credentials. I'm still investigating a behavior where I'm getting an error after credentials expire unable to access s3. I can see the POST request in the bifrost logs but sill getting errors in mattermost to do write operations. After restarting bifrost pods it works again. I'll close this PR and open a new one if needed. Thanks @agnivade

**Comment by agnivade** [comment]
Happy to take a look at the full logs from bifrost and Mattermost. Or if you want to investigate this some more by yourself, that's fine as well!

**Comment by andrleite** [comment]
> Happy to take a look at the full logs from bifrost and Mattermost. Or if you want to investigate this some more by yourself, that's fine as well!

Thanks @agnivade I'll create a separate environment to replicate the issue and try to do a deeper investigation. I'll ping you to share the results.

**Pull request closed without merging**
